hwjma_basic_config.settings_form:
  title: 'Basic Configration setting'
  route_name: hwjma_basic_config.settings_form
  description: 'A description for the menu entry'
  parent: system.admin_config_system
  weight: 99
